# refer to: https://github.com/coq-community/templates/blob/master/ref.yml
---
fullname: "fullname" # TODO: This software's name
organization: diohabara # TODO: GitHub organization
namespace: namespace # TODO: `name` in theories/dune
shortname: "short" # TODO: Repository name
action: true
nix: true
dune: true
coqdoc: false
community: false

synopsis: "synopsis" #TODO:

description: |- # TODO:
  "description"

authors: # TODO:
  - name: Takemaru Kadoi
    initial: false

maintainers: # TODO:
  - name: Takemaru Kadoi
    nickname: diohabara

opam-file-maintainer: diohabara@gmail.com # TODO:

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.15 or later
  opam: '{(>= "8.15")}'

tested_coq_nix_versions:
  - coq_version: "8.15"

documentation: |-
  ## Documentation

  ### How to generate files

  ```shell
  TMP=$(mktemp -d); git clone https://github.com/coq-community/templates.git $TMP
  nix-shell -p mustache-go --run $TMP/generate.sh
  ```
---

