# run the below command:
# nix-shell -p mustache-go --run "$TMP/generate.sh .github/workflows/nix-action.yml theories/dune dune-project README.md"
---
fullname: "fullname" # TODO:
shortname: "short" # TODO:
organization: diohabara # TODO:
action: true
nix: true
dune: true
coqdoc: true

synopsis: "synopsis" #TODO:

description: |- # TODO:
  "description"

authors: # TODO:
  - name: Takemaru Kadoi
    initial: false

maintainers: # TODO:
  - name: Takemaru Kadoi
    nickname: diohabara

opam-file-maintainer: diohabara@gmail.com # TODO:

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.14 or later
  opam: '{(>= "8.14" & < "8.16~") | (= "dev")}'

supported_ocaml_versions:
  text: 4.12 or later
  opam: '{(>= "4.12" & < "4.14") | (= "dev")}'

tested_coq_opam_versions:
  - version: dev
  - version: "8.15"
  - version: "8.14"

tested_coq_nix_versions:
  - coq_version: "8.15"

---

